### ISSUE TITLE
Front Camera in my Nexus 5

### ISSUE THREAD

**Issue by manugildev** [AkramaMirza/snapchat#1]
Hi, I was playing with your code for a bit, because I want to make a camera app and I don't know why. When I switch the camera from BackCamera to Front one it closes the app.

```
java.lang.RuntimeException: setParameters failed
      at android.hardware.Camera.native_setParameters(Native Method)
      at android.hardware.Camera.setParameters(Camera.java:1878)
      at com.akramamirza.photobabble.CameraTextureView$1.run(CameraTextureView.java:112)
      at java.lang.Thread.run(Thread.java:818)
```

**Comment by manugildev** [comment]
Hi there, so in CameraTextureView.java when you are setting the parameters for the camera you need to check if focus continuous mode is available, cause in the front facing camera you don't have that mode and that's why is crashing the app. 

```
if(parameters.getSupportedFocusModes().contains(Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE)){   
    parameters.setFocusMode(Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE);
}
```
